version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: edupay-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edupay
    ports:
      - "5432:5432"
    volumes:
      - edupay-db-data:/var/lib/postgresql/data

volumes:
  edupay-db-data: